# Generated by Django 2.2.2 on 2019-08-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions_core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='q',
        ),
    ]
