# Generated by Django 2.2.2 on 2019-08-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions_core', '0003_auto_20190816_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentity',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timelineentity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='actions_core.Organization'),
        ),
    ]
