# Generated by Django 2.2.2 on 2019-08-15 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions_core', '0005_auto_20190816_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineentity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entities', to='actions_core.User'),
        ),
    ]
