# Generated by Django 2.2.2 on 2019-08-16 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions_core', '0007_auto_20190816_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='actions_core.Organization'),
            preserve_default=False,
        ),
    ]
